spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hrm
    password: t6B2nEgqwHEV08M2
    # useAffectedRows=true ：参数设为 true，表示操作数据库时返回的为影响的行数，否则mybatis返回的是匹配的行数
    url: jdbc:mysql://47.96.164.65/hrm_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
  redis:
    host: 47.96.164.65
    port: 6379
    password: xiaoyu
    timeout: 3000
  # 指定生产环境
  profiles:
    active: prod
server:
  port: 8080
# 配置 开启驼峰命名的方法
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

# 存储在redis中的用户信息 key 前缀
XIAOYU_USER: user_inf

# 文件上传路径
FILE_PATH: C:/Users/Yuqiang/IdeaProjects/xiaoyu-hrm/uploads/

# 指定日志的路径
logging:
  file:
    path: logs
  level:
    com.xiaoyu.hrm.mapper: debug

---

# 生产环境
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hrm
    password: t6B2nEgqwHEV08M2
    # useAffectedRows=true ：参数设为 true，表示操作数据库时返回的为影响的行数，否则mybatis返回的是匹配的行数
    url: jdbc:mysql://localhost/hrm_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
  redis:
    host: localhost
    port: 6379
    password: xiaoyu
    timeout: 3000
  profiles: prod
  servlet:
    multipart:
      # 上传文件的大小
      max-file-size: 10MB
      # 单个文件的大小
      file-size-threshold: 10MB

# 端口
server:
  port: 8080

# 配置
mybatis:
  # config-location 与 configuration 不同同时配置，负责mybatis不知道以哪个为准
  config-location: classpath:mybatis/mybatis-config.xml
  # spring boot集成mybatis的方式打印sql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名的方法
#    map-underscore-to-camel-case: true

# 存储在redis中的用户信息 key 前缀
XIAOYU_USER: user_inf
# 文件上传路径
FILE_PATH: /home/hrm/uploads/

# 指定日志的路径
logging:
  file:
    path: /home/hrm/logs
  level:
    com.xiaoyu.hrm.mapper: debug

